name = "TestPackage"
uuid = "f974a0ac-c093-42e7-b307-94889a9c0c6b"
authors = ["Augustinas Sukys"]
version = "0.0.1"

[deps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
SymbolicUtils = "0.8.0"
julia = "1.5"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
